# Generated by Django 5.1.1 on 2024-11-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('description_ru', models.CharField(max_length=255, verbose_name='Description in Russian')),
                ('description_en', models.CharField(max_length=255, verbose_name='Description in English')),
            ],
            options={
                'verbose_name': 'Email Section',
                'verbose_name_plural': 'Email Section',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Image')),
                ('desktop_height', models.PositiveIntegerField(default=386, verbose_name='Desktop Height')),
                ('desktop_width', models.CharField(choices=[('100', 'Full width'), ('40', 'Half width')], default='100', max_length=3, verbose_name='Desktop Width')),
                ('mobile_height', models.PositiveIntegerField(default=250, verbose_name='Mobile Height')),
            ],
            options={
                'verbose_name': 'Main Banner Section',
                'verbose_name_plural': 'Main Banner Section',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('description_ru', models.CharField(max_length=255, verbose_name='Description in Russian')),
                ('description_en', models.CharField(max_length=255, verbose_name='Description in English')),
            ],
            options={
                'verbose_name': 'Phone Section',
                'verbose_name_plural': 'Phone Section',
            },
        ),
        migrations.CreateModel(
            name='SingleBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='single_banner_image', verbose_name='Image')),
                ('header_text_ru', models.CharField(max_length=255, verbose_name='Header in Russian')),
                ('header_text_en', models.CharField(max_length=255, verbose_name='Header in English')),
            ],
            options={
                'verbose_name': 'Image Banner Section',
                'verbose_name_plural': 'Image Banner Section',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.ManyToManyField(to='contacts_page.email', verbose_name='Emails')),
                ('main_banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts_page.mainbanner', verbose_name='Main Banner')),
                ('phones', models.ManyToManyField(to='contacts_page.phone', verbose_name='Phones')),
                ('single_banner_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts_page.singlebannerimage', verbose_name='Image Banner')),
            ],
            options={
                'verbose_name': 'Contacts Page Widget',
                'verbose_name_plural': 'Contacts Page Widgets',
            },
        ),
    ]
