# Generated by Django 5.1.1 on 2024-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=5)),
                ('file', models.FileField(upload_to='banner/')),
                ('button', models.BooleanField(default=False)),
                ('height', models.PositiveIntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('icon', models.ImageField(upload_to='service-card/')),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('page', models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('portfolio', 'Portfolio'), ('reviews', 'Reviews'), ('blog', 'Blog')], default='home', max_length=20, unique=True)),
                ('cards', models.ManyToManyField(to='api.servicecard')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
