# Generated by Django 5.1.1 on 2024-11-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_projectsection_projects_delete_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
