# Generated by Django 5.1.1 on 2024-10-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_banner_servicecard_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('portfolio', 'Portfolio'), ('reviews', 'Reviews'), ('blog', 'Blog')], default='home', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=20, unique=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.banner')),
            ],
            options={
                'verbose_name': 'Page Banner',
                'verbose_name_plural': 'Page Banners',
                'unique_together': {('page', 'type')},
            },
        ),
    ]
