# Generated by Django 5.1.1 on 2024-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
