# Generated by Django 5.1.1 on 2024-11-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainBanner',
        ),
        migrations.DeleteModel(
            name='PageBanner',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
