# Generated by Django 5.1.1 on 2024-10-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pagebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='height',
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_height',
            field=models.PositiveIntegerField(default=500, verbose_name='Banner height on desktop in (px)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=300, verbose_name='Banner height on mobile in (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button',
            field=models.BooleanField(default=False, verbose_name='Show button - "Leave an application"'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Banner title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=5, verbose_name='Banner type'),
        ),
    ]
