# Generated by Django 5.1.1 on 2024-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_banner_height_banner_desktop_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicecard',
            name='name',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='name_en',
            field=models.CharField(default=1, max_length=256, verbose_name='Name in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecard',
            name='name_ru',
            field=models.CharField(default=1, max_length=256, verbose_name='Name in Russian'),
            preserve_default=False,
        ),
    ]
