# Generated by Django 5.1.1 on 2024-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_mainbanner_delete_pagebanner_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description_en',
            field=models.TextField(default='Furniture, doors, windows, walls, floors, ceilings and other surfaces restoration and repair in Moscow and Moscow region.', verbose_name='Description in English'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='description_ru',
            field=models.TextField(default='Реставрация и ремонт мебели, дверей, окон, стен, полов, потолков и других поверхностей в Москве и Московской области.', verbose_name='Description in Russian'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_en',
            field=models.CharField(default='Fixworks - restoration and repair', max_length=512, verbose_name='Title in English'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_ru',
            field=models.CharField(default='Fixworks - реставрация и ремонт', max_length=512, verbose_name='Title in Russian'),
        ),
    ]
