# Generated by Django 5.1.1 on 2024-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_banner_title_banner_title_en_banner_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Title in English'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Title in Russian'),
        ),
    ]
