# Generated by Django 5.1.1 on 2024-10-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_banner_title_en_alter_banner_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='type',
        ),
    ]
