# Generated by Django 5.1.1 on 2024-10-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_pagebanner_banner_pagebanner_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projectsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectsection',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Description in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Description in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_en',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='title_ru',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
    ]
