# Generated by Django 5.1.1 on 2024-10-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='position',
            new_name='location',
        ),
    ]
