# Generated by Django 5.1.1 on 2024-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_position_review_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment_en',
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
