# Generated by Django 5.1.1 on 2024-10-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_text_review_comment_en_review_comment_ru'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagebanner',
            unique_together=set(),
        ),
    ]
