# Generated by Django 5.1.1 on 2024-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_pagebanner_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Title in Russian')),
                ('title_en', models.CharField(max_length=512, verbose_name='Title in English')),
                ('description_ru', models.TextField(verbose_name='Description in Russian')),
                ('description_en', models.TextField(verbose_name='Description in English')),
                ('image', models.ImageField(upload_to='blog/')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
