# Generated by Django 5.1.1 on 2024-10-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='blog',
            name='first_paragraph_en',
            field=models.TextField(default=1, verbose_name='First paragraph in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='first_paragraph_ru',
            field=models.TextField(default=1, verbose_name='First paragraph in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='second_paragraph_en',
            field=models.TextField(default=1, verbose_name='Second paragraph in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='second_paragraph_ru',
            field=models.TextField(default=1, verbose_name='Second paragraph in Russian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='third_paragraph_en',
            field=models.TextField(default=1, verbose_name='Third paragraph in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='third_paragraph_ru',
            field=models.TextField(default=1, verbose_name='Third paragraph in Russian'),
            preserve_default=False,
        ),
    ]
