# Generated by Django 5.1.1 on 2024-10-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbanner',
            name='height',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='desktop_height',
            field=models.PositiveIntegerField(default=386),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=250),
        ),
    ]
