# Generated by Django 5.1.1 on 2024-10-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_feedback_feedbackfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=512, verbose_name='Question in Russian')),
                ('question_en', models.CharField(max_length=512, verbose_name='Question in English')),
                ('answer_ru', models.TextField(verbose_name='Answer in Russian')),
                ('answer_en', models.TextField(verbose_name='Answer in English')),
            ],
            options={
                'verbose_name': 'Restoration FAQ',
                'verbose_name_plural': 'Restoration FAQs',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Title in Russian')),
                ('title_en', models.CharField(max_length=512, verbose_name='Title in English')),
                ('description_ru', models.TextField(verbose_name='Description in Russian')),
                ('description_en', models.TextField(verbose_name='Description in English')),
            ],
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Name in Russian')),
                ('name_en', models.CharField(max_length=512, verbose_name='Name in English')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('title_ru', models.CharField(max_length=512, verbose_name='Title in Russian')),
                ('title_en', models.CharField(max_length=512, verbose_name='Title in English')),
                ('description_ru', models.TextField(verbose_name='Description in Russian')),
                ('description_en', models.TextField(verbose_name='Description in English')),
                ('seo_title_ru', models.CharField(max_length=512, verbose_name='SEO Title in Russian')),
                ('seo_title_en', models.CharField(max_length=512, verbose_name='SEO Title in English')),
                ('seo_description_ru', models.TextField(verbose_name='SEO Description in Russian')),
                ('seo_description_en', models.TextField(verbose_name='SEO Description in English')),
                ('image_before', models.ImageField(upload_to='restoration/')),
                ('image_after', models.ImageField(upload_to='restoration/')),
                ('image_title_ru', models.CharField(max_length=512, verbose_name='Image title in Russian')),
                ('image_title_en', models.CharField(max_length=512, verbose_name='Image title in English')),
                ('services_background', models.ImageField(upload_to='restoration/', verbose_name='Services background image')),
                ('faqs', models.ManyToManyField(blank=True, null=True, to='api.faq')),
            ],
            options={
                'verbose_name': 'Restoration',
                'verbose_name_plural': 'Restorations',
            },
        ),
        migrations.CreateModel(
            name='RestorationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Service title in Russian')),
                ('title_en', models.CharField(max_length=512, verbose_name='Service title in English')),
                ('description_ru', models.TextField(verbose_name='Service description in Russian')),
                ('description_en', models.TextField(verbose_name='Service description in English')),
                ('restoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.restoration')),
            ],
            options={
                'verbose_name': 'Restoration Service',
                'verbose_name_plural': 'Restoration Services',
            },
        ),
    ]
