# Generated by Django 5.1.1 on 2024-10-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_faq_seo_restoration_restorationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('portfolio', 'Portfolio'), ('reviews', 'Reviews'), ('blog', 'Blog'), ('contact', 'Contact')], default='home', max_length=20, unique=True),
        ),
    ]
