# Generated by Django 5.1.1 on 2024-10-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_seo_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
        migrations.AddField(
            model_name='restoration',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='restoration/', verbose_name='Banner image'),
        ),
        migrations.AddField(
            model_name='restoration',
            name='desktop_height',
            field=models.PositiveIntegerField(default=869),
        ),
        migrations.AddField(
            model_name='restoration',
            name='mobile_height',
            field=models.PositiveIntegerField(default=348),
        ),
    ]
