# Generated by Django 5.1.1 on 2024-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_seo_options_restoration_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='desktop_width',
            field=models.CharField(choices=[('100', 'Full width'), ('50', 'Half width')], default='100', max_length=3),
        ),
    ]
