# Generated by Django 5.1.1 on 2024-10-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_mainbanner_desktop_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoration',
            name='desktop_width',
            field=models.CharField(choices=[('100', 'Full width'), ('40', 'Half width')], default='100', max_length=3),
        ),
    ]
