# Generated by Django 5.1.1 on 2024-11-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_page', '0002_alter_projectspage_main_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project List'},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name': 'Project Details', 'verbose_name_plural': 'Project Details'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='main_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_page.mainbanner', verbose_name='Main Banner'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='single_banner_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_page.singlebannerimage', verbose_name='Image Banner'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='single_banner_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_page.singlebannervideo', verbose_name='Video Banner'),
        ),
    ]
