# Generated by Django 5.1.1 on 2024-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio List'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ru',
            field=models.CharField(default=1, max_length=512, verbose_name='Title in Russian'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Image'),
        ),
    ]
