# Generated by Django 5.1.1 on 2024-11-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoration_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restoration',
            options={'verbose_name': 'Restoration', 'verbose_name_plural': 'Restoration List'},
        ),
    ]
