# Generated by Django 5.1.1 on 2024-11-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restoration_page', '0001_initial'),
        ('reviews_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_image')),
                ('header_text_ru', models.CharField(max_length=255)),
                ('header_text_en', models.CharField(max_length=255)),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text_ru', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('desktop_height', models.PositiveIntegerField(default=386)),
                ('desktop_width', models.CharField(choices=[('100', 'Full width'), ('40', 'Half width')], default='100', max_length=3)),
                ('mobile_height', models.PositiveIntegerField(default=250)),
            ],
            options={
                'verbose_name': 'Main Banner',
                'verbose_name_plural': 'Main Banner',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='partners/')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners List',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=256, verbose_name='Name in Russian')),
                ('name_en', models.CharField(max_length=256, verbose_name='Name in English')),
                ('icon', models.ImageField(upload_to='service-card/')),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
            },
        ),
        migrations.CreateModel(
            name='SingleBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='single_banner_image')),
                ('header_text_ru', models.CharField(max_length=255)),
                ('header_text_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SingleBannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='single_banner_video')),
                ('header_text_ru', models.CharField(max_length=255)),
                ('header_text_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=256, verbose_name='Name in Russian')),
                ('name_en', models.CharField(max_length=256, verbose_name='Name in English')),
                ('icon', models.ImageField(upload_to='service-card/')),
                ('restoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoration_page.restoration')),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.aboutus')),
                ('counter_banner', models.ManyToManyField(to='home_page.counter')),
                ('reviews_banner', models.ManyToManyField(blank=True, null=True, to='reviews_page.review')),
                ('main_banner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.mainbanner')),
                ('partners_banner', models.ManyToManyField(blank=True, null=True, to='home_page.partner')),
                ('restoration_banner', models.ManyToManyField(blank=True, null=True, to='home_page.servicecard')),
                ('services_banner', models.ManyToManyField(blank=True, null=True, related_name='services_banner', to='home_page.servicecard')),
                ('single_banner_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.singlebannerimage')),
                ('single_banner_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.singlebannervideo')),
            ],
            options={
                'verbose_name': 'Home Page Widget',
                'verbose_name_plural': 'Home Page Widgets',
            },
        ),
    ]
