# Generated by Django 5.1.1 on 2024-11-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.aboutus'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='counter_banner',
            field=models.ManyToManyField(blank=True, null=True, to='home_page.counter'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.mainbanner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='single_banner_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.singlebannerimage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='single_banner_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.singlebannervideo'),
        ),
    ]
