# Generated by Django 5.1.1 on 2024-11-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_homepage_about_us_and_more'),
        ('restoration_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecard',
            name='restoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoration_page.restoration', to_field='slug'),
        ),
    ]
