# Generated by Django 5.1.1 on 2024-11-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_servicecard_restoration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecard',
            old_name='restoration',
            new_name='slug',
        ),
    ]
