# Generated by Django 5.1.1 on 2024-11-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_restoration_servicecard_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
