# Generated by Django 5.1.1 on 2024-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_alter_aboutus_options_alter_counter_options_and_more'),
        ('reviews_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='counter_banner',
            field=models.ManyToManyField(blank=True, to='home_page.counter', verbose_name='Counter Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='partners_banner',
            field=models.ManyToManyField(blank=True, to='home_page.partner', verbose_name='Partners Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='restoration_banner',
            field=models.ManyToManyField(blank=True, to='home_page.servicecard', verbose_name='Restoration Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews_banner',
            field=models.ManyToManyField(blank=True, to='reviews_page.review', verbose_name='Reviews Banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_banner',
            field=models.ManyToManyField(blank=True, related_name='services_banner', to='home_page.servicecard', verbose_name='Services Banner'),
        ),
    ]
