# Generated by Django 5.1.1 on 2024-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('comment_ru', models.TextField()),
                ('comment_en', models.TextField()),
                ('image', models.ImageField(upload_to='reviews/')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews Page',
            },
        ),
    ]
